### ISSUE TITLE
Reset of volume options after a TC ends

### ISSUE THREAD

**Issue by srijan-sivakumar** [gluster/glusto-tests#34] opened 2020-11-24 17:07 UTC
**Description of problem:** Current flow doesn't reset the cluster options in gluster after the TC ends which causes certain TC's to fail.

**Operating system**: ALL

**Python Version**: ALL

**Terminal dump of the issue observed:**:
<details>

</details>

**Exact glusto-tests log where the issue was observed:**:
<details>

</details>

**Setup info:**
<details>
Number of nodes:

Number of clients: NA

Number of servers: NA

Testcase or library: This affects all the TCs

How reproducible: For instance take the TC wherein the default value of Quorum value is being verified. If the Quorum option is set in a previous TC then it'll be carried on to the current TC.

</details>

**Additional info:**

**Comment by srijan-sivakumar** [comment] 2020-11-24 17:11
@aloganat @kshithijiyer I noticed this while working on a couple of cases, especially when we are setting certain cluster options in one TC, it is not reset to default. I think we can fix this by running the command, `gluster vol reset all` which would go on to reset all cluster options to default values. This can be done after the TC is ended, i.e. in the tearDown method within the TC.

**Comment by kshithijiyer** [comment] 2020-11-24 17:32
@srijan-sivakumar Feel free to add the code to reset volume options if you see any such test cases. We have done this exercise a couple of times now but if you still see any testcases feel free to send a patch or point them out here, one of us will do the needful.

[1] https://github.com/gluster/glusto-tests/commit/45ea4788b1f6d3a6fe4419e0aea9e68cf6aa062b
[2] https://github.com/gluster/glusto-tests/commit/1f3968667c7f3d9121df209d5f3ba7517d982eb8

**Comment by srijan-sivakumar** [comment] 2020-11-24 17:45
@kshithijiyer , I'm thinking of using the already existing function volume_reset(). This could be invoked with `all` in place of the `volume name` and that must do the job of resetting the cluster volume options ( All the cluster options would be reset in this case )

I think this approach would be easier rather than modifying and adding that in the TC logic as that'd mean we'd have to go through each TC to verify if that might be the case. Now in [1] and [2] I see that we're setting the `quorum ratio` to `51%` but when I try to use `gluster vol get all cluster.server-quorum-ratio` the result will be `51% (DEFAULT)`.

**Comment by srijan-sivakumar** [comment] 2020-11-24 18:01
Gerrit patch link : https://review.gluster.org/c/glusto-tests/+/25173

**Comment by kshithijiyer** [comment] 2020-11-24 18:24
It would be better to add the rest_volume() code only where it's needed instead of adding it to the base class itself. Also cluster level options can be set even without creating volumes, so it will still fail.

**Comment by srijan-sivakumar** [comment] 2020-11-25 04:43
Now that I think..yes. That's right, but my question is should we leave it to each TC to reset the cluster options or should it be part of the tearDown for all the TCs. Now it does make perfect sense to save some computation by not including it in every TC. But on the other hand, we'd be having a whole bunch of TCs to check and modify this. @kshithijiyer , what's your thought on this..

**Comment by kshithijiyer** [comment] 2020-11-25 05:02
It's a tricky one due to the following things:
1. If we add volume_reset() in cleanup_volume() the problem is we have test cases which alter quorum and do peer probe, such test cases will still fail.
2. We can add the code in teardown() in base class and it'll get automatically get invoked if we run cases but this approach has issues as we can hit timeout bugs as we are running `gluster v reset all all` after every tc. Also there is a high chance that it'll invoke memory leaks as far as I remember there are still some transactions which can cause memory leaks if we run them thousands of time.
3. Adding it to testcases seems like a optimal approach but we'll have to put in alot of effort to check all the cases and send a patch for it, one time effort but still a significant one.

@aloganat any thoughts on this?

**Comment by aloganat** [comment] 2020-11-25 05:44
@srijan-sivakumar @kshithijiyer When thinking of other concerns as kshithij mentioned, adding it to testcases seems to be optimal one. +1 for using volume_reset in the testcases wherever applicable rather than using it in teardown().

**Comment by srijan-sivakumar** [comment] 2020-11-25 05:51
@aloganat , I'll proceed accordingly. Will address only the TCs wherein the option is to be reset.

**Comment by aloganat** [comment] 2020-11-25 05:52
Thanks @srijan-sivakumar

**Comment by aloganat** [comment] 2020-12-02 04:59
As discussed, volume_reset will be added only in the required test cases. Hence, closing the issue.

**Closed by aloganat** 2020-12-02 04:59 UTC
