### ISSUE TITLE
Glusto removes all mountpoint

### ISSUE THREAD

**Issue by BarakSason** [gluster/glusto-tests#25] opened 2020-08-09 09:25 UTC
When running tests, on cleanup glusto performs 'rm -rf /mnt/*', which deletes **ALL** mountpoints.
E.g.:
2020-08-09 12:16:21,591 ERROR (scratch_cleanup) failed to unmount/already unmounted barak-pc
2020-08-09 12:16:21,591 INFO (run) root@barak-pc (cp): rm -rf /mnt/*

Glusto should only remove mountpoints used by it for running tests, and not delete data which is unrelated to it.

**Comment by kshithijiyer** [comment] 2020-08-10 03:46
Ideally glusto-tests should be run only on dedicated setups. It's not prescribed to run glusto-tests on setup which are running other tests, this is because the test results can be contaminated by the other volumes. 
This doesn't look like a issue.

@aloganat Please share your views on this and close the issue as not a bug.

**Comment by aloganat** [comment] 2020-08-11 18:35
@kshithijiyer Could we cleanup only the mounts that are created by glusto-tests? This could be done by reading the mount point data in config file.

**Comment by kshithijiyer** [comment] 2020-08-11 18:57
@aloganat From a test framework perspective it looks like a over kill. It would slow down the cleanup process slowing down the framework itself.

**Comment by BarakSason** [comment] 2020-08-11 19:13
@kshithijiyer This has nothing to do with manual testing - If I have other mountpoints mounted under /mnt (this can even be completely unrelated to Gluster - I can mount an external disk for that matter), then the test framework erases everything, including my data - this is not acceptable, nor correct behavior from an engineering POV. 
Any tool should NOT affect other data in the system (unless it's it direct purpose, which is not in that case).
As @aloganat mentioned, the framework needs to be modified in such a way that it keeps a list of created mountpoints in memory, and only deletes them on cleanup.

**Closed** 2020-11-23 20:00 UTC
Labels: wontfix
